version: "3"

services:
  web:
    image: djtdb-1:latest
    ports:
      - "0.0.0.0:8000:8000"
      # - "8000:8000"
    volumes:
      # - ../..:/workspaces 
      - type: bind
        source: /mnt/prismdb/prismrawstore/02_genetic/data/tileprism/
        # source: c:/Users/choosf/Documents/SECURE/PRISM/genomicspark/data/g1000/my_vcf_dataset
        target: /mnt/data/tileprism  
    command: ["sleep", "infinity"]
    # command: "python manage.py runserver 0.0.0.0:80 &"
    env_file:
      - .env.dev
