version: '3'

services:
  devcontainer:
    build: 
      context: ..
      dockerfile: .offlinedev/Dockerfile-py-django-noncached
    image: djtdb-dev
    volumes:
      - ../..:/workspaces
      - type: bind
        source: c:/Users/choosf/Documents/SECURE/PRISM/genomicspark/data/g1000/my_vcf_dataset
        target: /mnt/data/tileprism     
    # network_mode: service:db
    # command: sleep infinity
    ports:
      # - "127.0.0.1:80:80"
      - "127.0.0.1:8001:8001"
      # - "0.0.0.0:80:80"
      - "0.0.0.0:8001:8001"
    env_file:
      - .env.dev
    depends_on:
      - anno-db

  anno-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: annodb
      POSTGRES_USER: prism1
      POSTGRES_PASSWORD: iDvbooTZ7NkASZAlTL9k
    # ports:
    #   - "5432:5432"
    volumes:
      - ../postgres_data:/var/lib/postgresql/data/
    