version: '3'

services:
  devcontainer:
    build: 
      context: ..
      dockerfile: .offlinedev/Dockerfile-py-django-noncached
    image: djtdb-1
    volumes:
      - ../..:/workspaces
      - type: bind
        source: c:/Users/choosf/Documents/SECURE/PRISM/genomicspark/data/g1000/my_vcf_dataset
        target: /mnt/data/tileprism     
    # network_mode: service:db
    # command: sleep infinity
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:8000:8000"
      - "0.0.0.0:80:80"
      - "0.0.0.0:8000:8000"
    env_file:
      - .env.dev
