version: '3'

services:
  devcontainer:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile-py-django
    volumes:
      - ../..:/workspaces:cached 
      - type: bind
        source: c:/Users/choosf/Documents/SECURE/PRISM/genomicspark/data/g1000/my_vcf_dataset
        target: /mnt/data/tileprism     
    # network_mode: service:db
    command: ["sleep", "infinity"]
    ports:
      - "127.0.0.1:8000:8000"
      # - "127.0.0.1:80:80"
    env_file:
      - .env.dev
