version: '3'

services:
  devcontainer:
    image: devcontainer-devcontainer
    # build: 
    #   context: ..
    #   dockerfile: .devcontainer/Dockerfile-py-django
    volumes:
      - ../..:/workspaces:cached
      - type: bind
        source: c:/Users/choosf/Documents/SECURE/PRISM/genomicspark/data/g1000/my_vcf_dataset
        # source: /mnt/prismdb/prismrawstore/02_genetic/data/tileprism/
        target: /mnt/data/tileprism     
    # network_mode: service:db
    command: /bin/bash
    ports:
      # - "127.0.0.1:8001:8001"
      - "127.0.0.1:80:80"
    env_file:
      - .env.dev
