version: '3'

services:
  devcontainer:
    image: datastrat/djangotiledb:latest
    # build: 
    #   context: ..
    #   dockerfile: .devcontainer/Dockerfile-py-django
    # image: prism:devcontainer            
    volumes:
      - ../..:/workspaces:cached 
      - type: bind
        source: c:/Users/choosf/Documents/SECURE/PRISM/genomicspark/data/g1000/my_vcf_dataset
        target: /mnt/data/tileprism
      - type: bind
        source: c:/Users/choosf/Documents/SECURE/PRISM/external_databases
        target: /mnt/data/external_databases
      - type: bind
        source: C:\Users\choosf\Documents\pyprojects\alltiledbs\sqlite3\db.sqlite3
        target: /workspaces/sqlite3/db.sqlite3
    # network_mode: service:db
    working_dir: /workspaces/devcontainer/djangotiledb_project/
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    # command: ["sleep", "infinity"]
    ports:
      - "127.0.0.1:8000:8000"
      # - "127.0.0.1:80:80"
    env_file:
      - .env.dev
    depends_on:
      - anno-db

  anno-db:
    image: postgres
    restart: no
    environment:
      POSTGRES_DB: annodb
      POSTGRES_USER: prism1
      POSTGRES_PASSWORD: iDvbooTZ7NkASZAlTL9k
    # ports:
    #   - "5432:5432"
    volumes:
      - type: bind
        source: C:\Users\choosf\Documents\pyprojects\alltiledbs\devcontainer\postgres_data
        target: /var/lib/postgresql/data/
      # - ../postgres_data:/var/lib/postgresql/data/
    
# volumes:
#   postgres_data:

