# Generated by Django 4.1.3 on 2023-04-18 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteModel',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('chr', models.CharField(max_length=32)),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('ref', models.CharField(blank=True, max_length=64, null=True)),
                ('alt', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoteHistoryModel',
            fields=[
                ('notehistory_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('valid_from_date', models.DateTimeField()),
                ('valid_to_date', models.DateTimeField(null=True)),
                ('comment', models.TextField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_history_reverse', to='tilequery.notemodel')),
            ],
        ),
    ]
