# Generated by Django 4.1.3 on 2023-04-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilequery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notehistorymodel',
            name='valid_to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
