# Generated by Django 4.1.3 on 2023-04-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilequery', '0002_alter_notehistorymodel_valid_to_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notemodel',
            index=models.Index(fields=['chr', 'start'], name='tilequery_n_chr_9fc5f2_idx'),
        ),
    ]
