# Generated by Django 4.1.3 on 2023-04-19 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tilequery', '0003_notemodel_tilequery_n_chr_9fc5f2_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notehistorymodel',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notehistorymodel',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='note_history_reverse', to='tilequery.notemodel'),
        ),
        migrations.AlterField(
            model_name='notehistorymodel',
            name='valid_from_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
