# Generated by Django 4.1.3 on 2023-04-19 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilequery', '0004_alter_notehistorymodel_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notehistorymodel',
            name='valid_from_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='notehistorymodel',
            name='valid_to_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
