# Generated by Django 4.1.3 on 2023-02-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinvars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alleleid', models.IntegerField()),
                ('type', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=800)),
                ('geneid', models.IntegerField()),
                ('genesymbol', models.CharField(max_length=710)),
                ('hgnc_id', models.CharField(max_length=10)),
                ('clinicalsignificance', models.CharField(max_length=70)),
                ('clinsigsimple', models.IntegerField()),
                ('lastevaluated', models.CharField(max_length=12)),
                ('rsid', models.IntegerField()),
                ('nsvesv', models.CharField(max_length=10)),
                ('rcvaccession', models.CharField(max_length=597)),
                ('phenotypeids', models.CharField(max_length=4300)),
                ('phenotypelist', models.CharField(max_length=1450)),
                ('origin', models.CharField(max_length=55)),
                ('originsimple', models.CharField(max_length=19)),
                ('assembly', models.CharField(max_length=6)),
                ('chromosomeaccession', models.CharField(max_length=14)),
                ('chromosome', models.CharField(max_length=4)),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('referenceallele', models.CharField(max_length=12)),
                ('alternateallele', models.CharField(max_length=20)),
                ('cytogenetic', models.CharField(max_length=24)),
                ('reviewstatus', models.CharField(max_length=52)),
                ('numbersubmitters', models.IntegerField()),
                ('guidelines', models.CharField(max_length=35)),
                ('testedingtr', models.CharField(max_length=1)),
                ('otherids', models.CharField(max_length=4035)),
                ('submittercategories', models.IntegerField()),
                ('variationid', models.IntegerField()),
                ('positionvcf', models.IntegerField()),
                ('referenceallelevcf', models.CharField(max_length=100)),
                ('alternateallelevcf', models.CharField(max_length=100)),
                ('order', models.FloatField()),
            ],
        ),
        
    ]
