# Generated by Django 4.1.3 on 2023-02-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoquery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsid',
            name='rsid',
            field=models.CharField(blank=True, default=None, max_length=20),            
        ),
    ]
