# Generated by Django 4.1.3 on 2023-02-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoquery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosome', models.IntegerField()),
                ('source', models.CharField(max_length=19)),
                ('gene_type', models.CharField(max_length=21)),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('gene', models.CharField(max_length=127)),
                ('product', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Snps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsid', models.CharField(max_length=16)),
                ('chr', models.CharField(max_length=32)),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('ref', models.CharField(blank=True, max_length=64, null=True)),
                ('alt', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
