# Generated by Django 4.1.3 on 2023-02-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoquery', '0002_genes_snps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genes',
            name='gene',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='genes',
            name='gene_type',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='genes',
            name='product',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='genes',
            name='source',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
