# Generated by Django 4.1.3 on 2023-02-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoquery', '0003_alter_genes_gene_alter_genes_gene_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='snps',
            index=models.Index(fields=['chr', 'start'], name='annoquery_s_chr_ef6b6d_idx'),
        ),
    ]
