# Generated by Django 4.1.3 on 2023-02-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoquery', '0004_snps_annoquery_s_chr_ef6b6d_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clinvars',
            index=models.Index(fields=['chromosome', 'start'], name='annoquery_c_chromos_1e06f2_idx'),
        ),
        migrations.AddIndex(
            model_name='clinvars',
            index=models.Index(fields=['clinicalsignificance'], name='annoquery_c_clinica_b28c49_idx'),
        ),
    ]
