# Generated by Django 4.1.3 on 2023-02-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoquery', '0005_clinvars_annoquery_c_chromos_1e06f2_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='genes',
            index=models.Index(fields=['chromosome', 'start'], name='annoquery_g_chromos_209e01_idx'),
        ),
    ]
