# Generated by Django 4.1.3 on 2023-04-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoquery', '0006_genes_annoquery_g_chromos_209e01_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='snps',
            name='af',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
